
services:
  api:
    build: .
    container_name: dev-hub-api
    ports:
      - "8081:8081"
    #environment:
      #- SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/devhub_db
      #- SPRING_DATA_REDIS_HOST=redis
