server:
  port: "${PORT}"
  forward-headers-strategy: framework
spring:
  datasource:
    url: "${SPRING_DATASOURCE_URL}"
    username: "${SPRING_DATASOURCE_USERNAME}"
    password: "${SPRING_DATASOURCE_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: 6379
      password: ${SPRING_DATA_REDIS_PASSWORD}
      ssl:
        enabled: true

  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-vallues: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23lijaePf0jN5EYwFP
            client-secret: 498c7928e9a98d5fc95a2e2eb51acc7d5a79ab44
            scope:
              - user:email
              - read:user