name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Aqui dizemos ao GitHub para subir o banco e o redis para os testes
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: devuser
          POSTGRES_PASSWORD: devpassword
          POSTGRES_DB: devhub_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Run Tests with Maven
        run: mvn -B package --file pom.xml
        env:

          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/devhub_db
          SPRING_DATASOURCE_USERNAME: devuser
          SPRING_DATASOURCE_PASSWORD: devpassword
          SPRING_DATA_REDIS_HOST: localhost
          SPRING_DATA_REDIS_PORT: 6379